server:
  port: 8080

spring:
  datasource:
    username: root
    password: DYZ2019ZB
    url: jdbc:mysql://localhost:3306/arithmeticexam?useSSL=true&characterEncoding=UTF-8&allowMultiQuery=true&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false
    prefix:classpath: /templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5

#   mvc:
#     static-path-pattern=/static/**


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.dd.entity
#showSql
logging:
  level:
    com:
      dd:
        mapper : debug

